# Generated by Django 4.1.3 on 2022-11-23 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WorkHealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkHealth.option')),
            ],
        ),
        migrations.RenameModel(
            old_name='Admins',
            new_name='Admin',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='number_answers',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='result',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_title',
            field=models.CharField(default='Survey', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkHealth.result'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkHealth.staff'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkHealth.survey'),
        ),
        migrations.AddField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkHealth.question'),
        ),
    ]
